# Generated by Django 4.1.2 on 2022-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_youtubevideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='url',
            field=models.CharField(max_length=1500, unique=True),
        ),
    ]
