# Generated by Django 4.1.2 on 2023-08-09 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_youtubevideo_filesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('url', models.URLField()),
                ('date_added', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Запрос на скачивание',
                'verbose_name_plural': 'Запросы на скачивание',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='TelegramDownloadRequest',
            fields=[
                ('downloadrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='youtube.downloadrequest')),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
            ],
            bases=('youtube.downloadrequest',),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.youtubevideo'),
        ),
    ]
