# Generated by Django 4.1.2 on 2022-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtubevideo_description_youtubevideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
