# Generated by Django 4.1.2 on 2022-10-09 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_youtubevideo_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ('-date_added',), 'verbose_name': 'Видео с YouTube', 'verbose_name_plural': 'Видео с YouTube'},
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
