# Generated by Django 4.1.2 on 2022-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_alter_youtubevideo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
